name: todoapp

on:
  push:
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

# Dagger plan gets configured via client environment variables
env:
  # This needs to be unique across all of netlify.app
  APP_NAME: todoapp-dagger-europa
  NETLIFY_TEAM: dagger
  # Get one from https://app.netlify.com/user/applications/personal
  NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
  # GitHub Actions friendly logs
  DAGGER_LOG_FORMAT: plain

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install
        uses: dagger/dagger-for-github@v2
        with: 
          install-only: true
        # See all options at https://github.com/dagger/dagger-for-github
      - name: Deploy to Netlify
        with:
          workdir: pkg/universe.dagger.io/examples/todoapp
          args: dagger project update; do deploy