name: todoapp

on:
  push:
    paths: 
      - ".github/workflows/todoapp.yml"
      - "examples/todoapp/**"
    # Trigger this workflow only on commits pushed to the main branch
    branches:
      - main

# Dagger plan gets configured via client environment variables
env:
  # This needs to be unique across all of netlify.app
  APP_NAME: todoapp-ivorscott-test
  NETLIFY_TEAM: ivor-scott
  # GitHub Actions friendly logs
  DAGGER_LOG_FORMAT: plain

jobs:
  dagger:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        # See all options at https://github.com/dagger/dagger-for-github
      - name: Deploy to Netlify
        uses: dagger/dagger-for-github@v2
        with: 
          version: 0.2
          workdir: examples/todoapp
          cmds: |
            project update
            do deploy
        env:
          # Get one from https://app.netlify.com/user/applications/personal
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
